/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cqupt_garbagesorter_jni_Jnilib */

#ifndef _Included_com_cqupt_garbagesorter_jni_Jnilib
#define _Included_com_cqupt_garbagesorter_jni_Jnilib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cqupt_garbagesorter_jni_Jnilib
 * Method:    say_hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cqupt_garbagesorter_jni_Jnilib_say_1hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
